### ISSUE TITLE
Is it still working now?

### ISSUE THREAD

**Issue by sinjaemin** [webmsgr/discordTelnet#3]
Is it still working now?

I set 'dkey' but it doesn't work

Which of the 3 below is the 'dkey' you are talking about?

"1088601359336620***"

"1cc5ea21b5a7e9b81f1d5c9b20d3c95d0ee528d7eddb12778f3fc8a2b8bd9***"

"MTA4ODYwMTM1OTMzNjYyMDEyNA.GhjIQ4.M226mp9cWIg8EJf6tMnIFh12FHPOZT8Jsy*****"

I think it's probably the lowest

I ran Python by typing normally, but it doesn't work.

Ask a question using a translator
forgive me

-------------------------------------------------------------------------------------
I want to run a text mud game on discord using this program.

Hostname: ggai.tv
Port: 4000

can i access this?

**Comment by webmsgr** [comment]
Sorry, due to updates to the discord api, this program doesnt work, at all. I haven't touched this code in years and i don't plan to. Also you probably shouldn't post your discord bot's key, it lets anyone login as the bot.
